### ISSUE TITLE
Qbittorrent website doesn't load for me!

### ISSUE THREAD

**Issue by Grainlord** [thim0o/Google-Colab-QBittorrent#1]
Website 1 says check your SSH.
Website 2 doesn't load at all. It keeps giving not responding error

**Comment by thim0o** [comment]
Serveo (website 2)  was down, but it's back up now!

**Comment by Grainlord** [comment]
thank you very much for your work!

**Comment by yellowjacketcoder** [comment]
@grainlord Hey man, I saw you on one other repository. You said you got transmission-cli to work on colab, can you contact me and tell me how?

**Comment by Grainlord** [comment]
sorry for late reply, but using transmission cli is extremely easy!

mount your drive:-
from google.colab import drive
drive.mount('/content/drive')

then install transmission cli;-
!apt-get install transmission-cli

finally to download torrents use this command:-
!transmisson-cli -w 'content/drive/My Drive/Torrents' "" #Paste magnet link
in the quotation marks.


Aria also works extremely well as a cli torrent client so you should also
give that a look.
to get higher speed, you might need to make a config file for the
transmission-cli and change the port to something higher like around 50000+
because those ports are not monitored by the isp so throttling is
eliminated and you can also increase the number o connections to maximize
the download speed.

Pro tip: manually stop the cell running the torrent download every 10
minutes or so when downloading a big torrent like >50gb so that if your
runtime terminates on its own then you can resume the torrent from the last
point where you stopped the cell, saves time and bandwidth. you dont need
to do this usually but is a good tip.

My current goto is the Qbittorrent client by thim0o i have got the highest
speeds using it almost 1 gigabit downloading speeds. On a single torrent i
can easily get 50-60MB/s up/down given it has good amount of seeders. but
when you saturate the connection by multiple popular torrents you can
easily get 1 gigabit up/down. With transmission cli most i can get is
around 30-40MB/s. Aria also gives extremely good speeds. see for yourself
which one you like the most.
