### ISSUE TITLE
stopped working after few minutes

### ISSUE THREAD

**Issue by llGooglell** [thim0o/Google-Colab-QBittorrent#4]
after we install this on google drive, its work good but stopped after few minutes of working and servio URL goes invalid and we have to install it again.. please fix it.. and let us know.

**Comment by thim0o** [comment]
How much is 'a few minutes'? Google colab sessions are recycled after 90 minutes if you don't keep the tab open and after 12 hours if you do keep a tab open. It's not possible to change that.

**Comment by llGooglell** [comment]
i have used it, but how is it possible to keep running while tab is closed, dear sir can you please post a new thing a utorrent web-front based client for centos-7, its really needed, because i have too much vps in my pocket with centos 7, is there any torrent client which can be used on centos-7 as web-front based.

**Comment by thim0o** [comment]
It's not possible to keep it running more than 90 minutes if you close the tab.
