### ISSUE TITLE
Wrong file sizes.

### ISSUE THREAD

**Issue by stephanie00100** [thim0o/Google-Colab-QBittorrent#6]
I use the Rclone mount option, when Qbittorrent finishes downloading/moving onto seeding status? I check the Google Drive files and the sizes don't match. The files weren't transferred 100%.

**Comment by thegreatestminer** [comment]
@stephanie00100 Please, PLEASE do not directly download files onto a rclone mount. That will guarantee file corruption, as torrents constantly modify the files you are downloading in various parts, and rclone can not keep up at all.

I would recommend downloading files into a local directory, then then doing `rclone copy` instead once it finishes. It's pretty easy to set up in qBittorrent Web UI settings.

**Comment by thim0o** [comment]
By default qbittorrent downloads to a temp folder first (which is local storage).
If you don't change this setting everything should work fine.

**Comment by stephanie00100** [comment]
rclone_config_name:        smc
local_mount_location:      /content/udrive/

qbittorrent   savePath:     /content/udrive/ColabDownloads


qbittorrent status goes like this  downloading, moving, seeding. I look inside google drive and something wasn't transferred 100%.  I haven't touched the settings inside of qbittorrent itself.

nohup.out shows this error, i left out the filename

2019/11/06 19:58:58 ERROR : ColabDownloads/*****************.mkv: WriteFileHandle.Write: error: Bad file descriptor

**Comment by yellowjacketcoder** [comment]
qBittorrent save path should not be /content/udrive.....

qBittorrent save path should be /content/qbittorrent....

After the download is completed, stop the torrent in qBT and then use `rclone copy` to move it to /content/udrive....
