### ISSUE TITLE
nohup: appending output to 'nohup.out'

### ISSUE THREAD

**Issue by VsR13** [thim0o/Google-Colab-QBittorrent#9]
i uploaded the rclone conf but when i ran the cell next to it , it gave me this error :
Not succeeded. No files or directories in mounted location. 
Check your config name and content. If the rclone command was not found, run the cell above.

log:
 2020/06/23 15:24:18 Failed to create file system for "rclone:": didn't find section in config file
. Would be really great if you could make a setup/procedure documentation

**Comment by thim0o** [comment]
There are instructions on how to create a config on the rclone website:
https://rclone.org/docs/
